name: Build VPK

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  release:
    types: [ published, created ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITASDK: /usr/local/vitasdk
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install VitaSDK
        run: |
          echo "VITASDK=$VITASDK" >> $GITHUB_ENV
          echo "$VITASDK/bin" >> $GITHUB_PATH
          
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          chmod +x bootstrap-vitasdk.sh install-all.sh vdpm
          ./bootstrap-vitasdk.sh
          ./install-all.sh
          
          # Install required packages
          ./vdpm vita2dlib
          ./vdpm ftpvita
          ./vdpm libarchive
          ./vdpm libjpeg-turbo
          ./vdpm libpng
          ./vdpm libvorbis
          ./vdpm libogg
          ./vdpm onigmo
          ./vdpm quirc
          ./vdpm zlib
          ./vdpm libexpat
          ./vdpm bzip2
          ./vdpm xz
          ./vdpm openssl

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cd modules/kernel && make -j$(nproc)
          cd ../patch && make -j$(nproc)
          cd ../usbdevice && make -j$(nproc)
          cd ../user && make -j$(nproc)
          cd ../.. && make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VitaShell.vpk
          path: build/VitaShell.vpk
          if-no-files-found: error
          
      - name: Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: build/VitaShell.vpk
          fail_on_unmatched_files: true
